http_handler: echo

cache: redis  # redis, memory, disable

handler:
  authentication: v1
  product: v1
  user: v1

service:
  authentication: v1
  product: v1
  user: v1

repository:
  authentication: postgres
  product: postgres
  user: postgres